dropout: 0
output_size: 6
num_classes: 6
distance_th_classification: manual
hidden_layers: 3
layers: 128
model_type: gnn
sample: True
pool_ratio: 0.8
pool_policy: all
ca_pred: True
cb_pred: False
omega_pred: False
theta_pred: False
phi_pred: False
loss_head_weights: [1, 1, 1, 1, 1]
debug: False
data_type: Train
similarity_clear: 0.05
dataset: separate_graphs_39f_12t_dataset
node_feat: 39
is_connected: False
base_lr: 0.001
momentum: 0.9
weight_decay: 0.00001
optimizing_method: adam
scheduler: None
steps: None
gamma: 0.2
batch_size: 48
epochs: 50
hparam_method: None
hparam_tune: False
loss_type: bce
weight: False
name: None
transform: True
angles: regression
