MODEL:
  DROPOUT: 0.0
  INPUT_SIZE: 363
  OUTPUT_SIZE: 1
  NUM_CLASSES: 2
  DISTANCE_TH_CLASSIFICATION: [18]
  HIDDEN_LAYERS: 3
  LAYERS: 128
  BATCHNORM: True
  TYPE: gnn
  SAMPLE: True
  POOL_RATIO: 0.8
  POOL_POLICY: all
DATA:
  FEATURES: processed_features_trainset
  LABELS: processed_labels_trainset
  DISTANCES: processed_dist_trainset
  TYPE: TRAIN
  TRANSFORM: flip
  MEAN: 0.21694291786377354
  STD: 0.49163950469350526
  FILTER: lysine
  SIMILARITY_CLEAR: 0.05
  DATASET: onehot_graph_dataset
  NODE_FEAT: 18
  IS_CONNECTED: False
TEST:
  FEATURES: processed_features_testset
  LABELS: processed_labels_testset
  DISTANCES: dist_testset
SOLVER:
  BASE_LR: 0.0005
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  OPTIMIZING_METHOD: adam
  SCHEDULER: None
  STEPS: None
  GAMMA: 0.2
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 2
  EVAL_PERIOD: 1
  HPARAM_METHOD: None
  HPARAM_TUNE: False
LOSS:
  TYPE: bce
  WEIGHT: True
NAME: all_processed_objects
