dropout: 0
output_size: 4
num_classes: 4
distance_th_classification: None
hidden_layers: 2
layers: 256
model_type: gnn
sample: True
pool_ratio: 0.8
pool_policy: all
ca_pred: True
cb_pred: False
omega_pred: False
theta_pred: False
phi_pred: False
loss_head_weights: [1, 0.1 , 1, 1, 1]
debug: False
data_type: Train
similarity_clear: 0.05
dataset: 39f_5A_dataset
node_feat: 39
is_connected: False
base_lr: 0.001
momentum: 0.9
weight_decay: 0
optimizing_method: adam
scheduler: None
steps: None
gamma: 0.2
batch_size: 8
epochs: 50
hparam_method: None
hparam_tune: False
loss_type: bce
weight: True
name: None
transform: True
angles: regression
sample_weight: False
multi_gpu: False
calibrate_model: start
gnn_type: gat
activation: relu
batchnorm: False
attention_heads: 6