dropout: 0
output_size: 4
num_classes: 4
distance_th_classification: manual
hidden_layers: 3
layers: 512
model_type: gnn
sample: True
pool_ratio: 0.6
pool_policy: all
ca_pred: True
cb_pred: False
omega_pred: False
theta_pred: False
phi_pred: False
loss_head_weights: [1, 0.1 , 1, 1, 1]
debug: False
data_type: Train
similarity_clear: 0.05
dataset: 44f_3A_intra_lys_dataset
node_feat: 44
is_connected: False
base_lr: 0.001
momentum: 0.9
weight_decay: 0.0001
optimizing_method: adamw
scheduler: None
steps: None
gamma: 0.2
batch_size: 80
epochs: 50
hparam_method: None
hparam_tune: False
loss_type: bce
weight: True
name: intra_overfit_model
transform: True
angles: regression
sample_weight: False
multi_gpu: False
calibrate_model: None
gnn_type: gat
activation: prelu
batchnorm: False
attention_heads: 6
features: {mol2, charge, asa, radius, res_type, anchor, id}
spacer_feture: True
xl_type_feature: False
global_pool_func: sum
is_ca_pool: False
fine_tune: False
attn_dropout: 0.3