MODEL:
  DROPOUT: 0.0
  OUTPUT_SIZE: 1
  NUM_CLASSES: 2
  DISTANCE_TH_CLASSIFICATION: [18]
  HIDDEN_LAYERS: 3
  LAYERS: 128
  TYPE: gnn
  SAMPLE: True
  POOL_RATIO: 0.8
  POOL_POLICY: all
  CB_PRED: False
  OMEGA_PRED: False
  THETA_PRED: False
  PHI_PRED: False
  LOSS_HEAD_WEIGHTS: [1, 0.2, 0.2, 0.2, 0.2]
  DEBUG: False
DATA:
  TYPE: TRAIN
  SIMILARITY_CLEAR: 0.05
  DATASET: separate_graphs_39f_12t_dataset
  NODE_FEAT: 39
  IS_CONNECTED: False
SOLVER:
  BASE_LR: 0.0005
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  OPTIMIZING_METHOD: adam
  SCHEDULER: None
  STEPS: None
  GAMMA: 0.2
TRAIN:
  BATCH_SIZE: 54
  EPOCHS: 100
  HPARAM_METHOD: None
  HPARAM_TUNE: False
LOSS:
  TYPE: bce
  WEIGHT: True
NAME: all_processed_objects
