MODEL:
  DROPOUT: 0.0
  INPUT_SIZE: 363
  OUTPUT_SIZE: 3
  NUM_CLASSES: 3
  DISTANCE_TH_CLASSIFICATION: [12, 19]
  HIDDEN_LAYERS: 3
  LAYERS: 128
  BATCHNORM: True
  TYPE: gnn
  SAMPLE: True
  POOL_RATIO: 0.8
DATA:
  FEATURES: processed_features_trainset
  LABELS: processed_labels_trainset
  DISTANCES: processed_dist_trainset
  TYPE: TRAIN
  TRANSFORM: flip
  MEAN: 0.21694291786377354
  STD: 0.49163950469350526
  FILTER: lysine
  SIMILARITY_CLEAR: 0.05
  DATASET: regular
  NODE_FEAT: 18
TEST:
  FEATURES: processed_features_testset
  LABELS: processed_labels_testset
  DISTANCES: dist_testset
SOLVER:
  BASE_LR: 0.0005
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  OPTIMIZING_METHOD: adam
  SCHEDULER: None
  STEPS: None
  GAMMA: 0.2
TRAIN:
  BATCH_SIZE: 46
  EPOCHS: 50
  EVAL_PERIOD: 1
  HPARAM_METHOD: None
  HPARAM_TUNE: False
LOSS:
  TYPE: bce
  WEIGHT: True
NAME: all_processed_objects
RAW_DATA:
  FEATURES_LIST: processed_features
  KEYS_LIST: processed_keys
  DIST_LIST: processed_dist
  LABEL_LIST: processed_labels