program: train.py
method: random
project: xl_gnn
entity: seanco
parameters:
  num_classes:
    value: 2
  dropout:
    value: 0.0
  output_size:
    value: 3
  distance_th_classification:
    values: [None, manual]
  hidden_layers:
    values: [3, 4]
  layers:
    value: 128
  model_type:
    value: gnn
  sample:
    value: True
  pool_ratio:
    values: [0, 0.4, 0.6, 0.8]
  pool_policy:
    value: all
  ca_pred:
    value: True
  cb_pred:
    values: [True, False]
  omega_pred:
    values: [True, False]
  theta_pred:
    values: [True, False]
  phi_pred:
    values: [True, False]
  loss_head_weights:
    values: [[1, 0.15, 0.225, 0.225, 0.45], [1, 0.1, 0.15, 0.15, 0.3], [1, 0.25, 0.375, 0.375, 0.75],
      [1, 0.05, 0.075, 0.075, 0.15]]
  debug:
    value: False
  data_type:
    value: Train
  similarity_clear:
    value: 0.05
  dataset:
    value: separate_graphs_39f_12t_dataset
  node_feat:
    value: 39
  is_connected:
    value: False
  base_lr:
    values: [0.001, 0.0005]
  momentum:
    value: 0.9
  weight_decay:
    values: [0, 0.00001]
  optimizing_method:
    value: adam
  scheduler:
    value: None
  steps:
    value: None
  gamma:
    value: 0.2
  batch_size:
    value: 84
  epochs:
    value: 50
  hparam_method:
    value: sweeps
  hparam_tune:
    value: False
  loss_type:
    value: bce
  weight:
    values: [True, False]
  name:
    value: all_processed_objects
  transform:
    value: True
  angles:
    value: regression